name: Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [amd64, arm64]
        os: [linux, darwin]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        cache: false
        go-version: '1.25'

    - name: Build the binary
      run: |
        GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o spongecase_${{ matrix.os }}_${{ matrix.arch }} main.go

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: spongecase_${{ matrix.os }}_${{ matrix.arch }}
        path: spongecase_${{ matrix.os }}_${{ matrix.arch }}

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: binaries

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          files: binaries/*
          prerelease: ${{ contains(github.ref, '-') }}
